electric <- read.table("household_power_consumption.txt", header = TRUE, sep = ";")
data <- subset(electric, Date=="1/2/2007" | Date == "2/2/2007")
head(data)
Global_active_power <- as.numeric(as.character(data$Global_active_power))
datetime <- strptime(paste(data$Date, data$Time), "%d/%m/%Y %H:%M:%S")
plot(datetime, Global_active_power, type = "l", xlab = "", ylab = "Global Active Power(kilowatts)")
dev.copy(png, file = "plot2.png", height = 480, width = 480)
dev.off()