electric <- read.table("household_power_consumption.txt", header = TRUE, sep = ";")
data <- subset(electric, Date=="1/2/2007" | Date == "2/2/2007")
head(data)
Global_active_power <- as.numeric(as.character(data$Global_active_power))
datetime <- strptime(paste(data$Date, data$Time), "%d/%m/%Y %H:%M:%S")
subMetering1 <- as.numeric(as.character(data$Sub_metering_1))
subMetering2 <- as.numeric(as.character(data$Sub_metering_2))
subMetering3 <- as.numeric(as.character(data$Sub_metering_3))
Voltage <- as.numeric(as.character(data$Voltage))
Global_reactive_power <- as.numeric(as.character(data$Global_reactive_power))
par(mfcol = c(2,2))
plot(datetime, Global_active_power, type = "l", xlab = "", ylab = "Global Active Power(kilowatts)")
plot(datetime, subMetering1, type = "l", xlab = "", ylab = "Energy Submetering")
lines(datetime, subMetering2, type = "l", col = "red")
lines(datetime, subMetering3, type = "l", col = "blue")
legend("topright", lty = 1, c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "red", "blue"))
plot(datetime, Voltage, type = "l")
plot(datetime, Global_reactive_power, type = "l")
dev.copy(png, file = "plot4.png", height = 480, width = 480)
dev.off()