electric <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?")
data <- subset(electric, Date=="1/2/2007" | Date == "2/2/2007")
head(data)
Global_active_power <- as.numeric(as.character(data$Global_active_power))
datetime <- strptime(paste(data$Date, data$Time), "%d/%m/%Y %H:%M:%S")
subMetering1 <- as.numeric(as.character(data$Sub_metering_1))
subMetering2 <- as.numeric(as.character(data$Sub_metering_2))
subMetering3 <- as.numeric(as.character(data$Sub_metering_3))
plot(datetime, subMetering1, type = "l", xlab = "", ylab = "Energy Submetering")
lines(datetime, subMetering2, type = "l", col = "red")
lines(datetime, subMetering3, type = "l", col = "blue")
legend("topright", lty = 1, c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "red", "blue"))
dev.copy(png, file = "plot3.png", height = 480, width = 480)
dev.off()